### PR TITLE
Pre hash columns before committing to wal

### LINKED ISSUE #685: Move prehash function to happen before write to WAL
Right now we support pre-hashing columns to speed up aggregation by storing the hash of the column directly.

However we perform this prehashing after writing to the WAL, which means during replay we no longer prehash the column.

We should prehash the data before writing to the WAL, that way the WAL has the prehashed data and theirs no problem with directly inserting afterwards.

### PR DESCRIPTION
**Pull request by gernest**
Closes #685

### CODE REVIEW

**Review by thorfour — APPROVED** [review]
Thanks!

**Comment by asubiotto** [comment]
I think there's also a TODO we can delete in db.go. I don't see any prehashing in the recovery path though, am I missing something?

**Comment by gernest** [comment]
> I think there's also a TODO we can delete in db.go. I don't see any prehashing in the recovery path though, am I missing something?

@asubiotto can you share the link to this so I can take a look?

**Comment by asubiotto** [comment]
https://github.com/polarsignals/frostdb/blob/67e37c6b4582b0a8b7f592d909aadca299b7b9c7/db.go#L913

**Comment by gernest** [comment]
thanks

**Pull request merged**
