### PR TITLE
Remove Unsafe* method from *OptInt32Builder

### PR DESCRIPTION
**Pull request by gernest**

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
Do we have to make similar changes to the other builders?

**Comment by gernest** [comment]
> Do we have to make similar changes to the other builders?

I don't know, this is the only opt builder I have touched.

**Comment by gernest** [comment]
I rebased on `main` to fix merge conflict.

**Comment by metalmatze** [comment]
Very cool! LGTM.

**Comment by gernest** [comment]
@thorfour can you please help merge this ? There is no any further changes required, instead of leaving it here to rot, we can close it if it has no merit.

Checking other opt builder is a separate task that has nothing to do with this PR.

**Comment by thorfour** [comment]
Yup I can merge this today

**Pull request merged**
