### PR TITLE
*: fix all lint issues

### PR DESCRIPTION
**Pull request by asubiotto**
This PR fixes all the lint issues reported by golangci-lint that have creeped into the codebase over time as well as ignoring lint issues that would take too long to fix.

My idea is to make passing golangci-lint a required step before merging, otherwise there doesn't seem to be much use in having a linter.

### CODE REVIEW

**Comment by metalmatze** [comment]
Oh wow. Yes we should totally make it a required step. 
Do you want to do it in this PR or follow up?

**Review by metalmatze — APPROVED** [review]

**Comment by asubiotto** [comment]
I don't think I have the necessary permissions to do this (it can be found under the repo's settings tab->code and automation)

**Comment by metalmatze** [comment]
> I don't think I have the necessary permissions to do this (it can be found under the repo's settings tab->code and automation)

Added the `lint` and `build` steps to be required.

**Comment by asubiotto** [comment]
Thanks!

**Pull request merged**
