### PR TITLE
Replace atomic unsafe pointers with generic atomic pointers

### PR DESCRIPTION
**Pull request by Mihai22125**
Replace atomic unsafe pointers with generic atomic pointers.

First-time contributor, so any feedback is more than welcome!

This resolves: #157.

### CODE REVIEW

**Comment by thorfour** [comment]
This looks great! Thanks for the contribution

**Comment by brancz** [comment]
Looks like we need to upgrade to go1.19, do you mind taking care of that @Mihai22125?

**Comment by Mihai22125** [comment]
Sure thing

**Comment by thorfour** [comment]
>   Error: `sync/atomic` is in the blacklist: Use go.uber.org/atomic instead of sync/atomic (depguard)

Looks like its necessary to update the `.golangci.yml` file

**Comment by Mihai22125** [comment]
Hi @thorfour, Thanks for the point. 

I updated the  `.golangci.yml` file. Can you check if it's alright now?

**Comment by thorfour** [comment]
```
   Error: copylocks: NewPartList passes lock by value: sync/atomic.Pointer[github.com/polarsignals/frostdb.Node] contains sync/atomic.noCopy (govet)
  Error: copylocks: literal copies lock value from next: sync/atomic.Pointer[github.com/polarsignals/frostdb.Node] contains sync/atomic.noCopy (govet)
  Error: copylocks: call of NewPartList copies lock value: sync/atomic.Pointer[github.com/polarsignals/frostdb.Node] contains sync/atomic.noCopy (govet)
  Error: copylocks: literal copies lock value from index: sync/atomic.Pointer[github.com/google/btree.BTree] contains sync/atomic.noCopy (govet)
  ```
  
  Now it's mad about copying locks

**Comment by Mihai22125** [comment]
The errors should be fixed now, please let me know if there are any issues left.

**Comment by thorfour** [comment]
Closing in favor of https://github.com/polarsignals/frostdb/pull/203 thanks for the contribution @Mihai22125

**Comment by Mihai22125** [comment]
Hi! I'm glad I could help

**Pull request closed without merging**
