### PR TITLE
*: check rows are sorted on insert

### PR DESCRIPTION
**Pull request by asubiotto**
This commit checks that an invariant we expect, that rows are sorted on insert, is upheld. If not, this commit increments a metric and sorts the rows.

### CODE REVIEW

**Review by metalmatze — APPROVED** [review]
Nice. Makes sense. 
We also have a metric for the total amount of inserted rows so we can nicely calculate the percentage of sorted rows :+1:

**Comment by asubiotto** [comment]
I'm going to hold off on merging until I investigate things a little more, looks like the check is failing on some wals and I want to make sure things are ironed out first.

**Comment by asubiotto** [comment]
In any case, it seems like this `IsSorted` check is very expensive (doubles replay times), so either we make it cheaper (which the whole database will benefit from) or we put this behind a debug tag.

**Comment by asubiotto** [comment]
This PR is ready for a review again! I added `log(n)` inserts that without the `IsSorted` check really improve replay times:
```
name      old time/op    new time/op    delta
Replay-8     60.6s ± 2%     40.5s ± 1%  -33.14%  (p=0.008 n=5+5)

name      old alloc/op   new alloc/op   delta
Replay-8    87.3GB ± 1%    66.0GB ± 0%  -24.35%  (p=0.008 n=5+5)

name      old allocs/op  new allocs/op  delta
Replay-8     1.10G ± 0%     0.73G ± 0%  -33.69%  (p=0.008 n=5+5)
```

However, with the addition of `IsSorted`, these two commits make it so that basically the check is free. I would advocate for merging this and removing the check once we are certain we have no more unsorted inserts (I think views are the last place where we insert unsorted rows):
```
name      old time/op    new time/op    delta
Replay-8     60.6s ± 2%     60.1s ± 2%   ~     (p=0.310 n=5+5)

name      old alloc/op   new alloc/op   delta
Replay-8    87.3GB ± 1%    87.3GB ± 1%   ~     (p=0.690 n=5+5)

name      old allocs/op  new allocs/op  delta
Replay-8     1.10G ± 0%     1.10G ± 0%   ~     (p=0.841 n=5+5)
```

**Comment by asubiotto** [comment]
I think there are even more improvements we can make in the insert path, but this is fine for now.

**Review by brancz — APPROVED** [review]
Makes so much sense 🤯

**Pull request merged**
