### PR TITLE
logictest: move distinct tests to logictest format

### PR DESCRIPTION
**Pull request by asubiotto**

### CODE REVIEW

**Comment by asubiotto** [comment]
We're seeing the PR fail because of ordering issues where tests have different row groups. This is because we don't enforce ordering on the row groups scanned when concurrency is enabled. Will need to fix the testing harness to not care about ordering.

**Comment by asubiotto** [comment]
OK, I just added another commit to ignore output ordering. If CI ends up green, this is RFAL.

**Review by metalmatze — APPROVED** [review]
Amazing stuff! :rocket:

**Comment by asubiotto** [comment]
TFTR!

**Pull request merged**
